"""Create co2_record table

Revision ID: a355e82efb61
Revises: e975278cd1d4
Create Date: 2024-09-11 13:10:39.242050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a355e82efb61'
down_revision = 'e975278cd1d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('co2_record', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=13),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('co2_record', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(length=13),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
